name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Alterar caso gere problemas nos computadores do laboratorio
        distribution: 'temurin'

    - name: Compile Java Code
      run: |
        mkdir -p bin
        javac -d bin -cp lib/junit-platform-console-standalone-1.11.0.jar *.java

    - name: Run Tests
      run: |
        java -cp bin:lib/junit-platform-console-standalone-1.11.0.jar org.junit.platform.console.ConsoleLauncher --scan-classpath
